{% set name = "torch_scatter" %}
{% set version = "2.0.7" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 369184948c838f756eea10464a3fbf8e103e22dc94d7045dbab85b5748bf85f9

build:
  number: 1
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version not in (undefined, 'None')]
    - export CC="$GCC"         # [linux64 and cuda_compiler_version not in (undefined, 'None')]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pytorch 1.8                            # [build_platform != target_platform]
    - pytorch-cpu                            # [build_platform != target_platform and osx or cuda_compiler_version in (undefined, 'None')]
    - pytorch-gpu                            # [build_platform != target_platform and cuda_compiler_version not in (undefined, 'None')]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
  host:
    - python
    - pip
    # pytorch 1.8 is the latest supported version of conda-forge at build time
    - pytorch 1.8
    - pytorch-gpu  # [cuda_compiler_version not in (undefined, 'None')]
    - pytorch-cpu  # [osx or cuda_compiler_version in (undefined, 'None')]
    - pytest-runner
  run:
    - python
    - {{ pin_compatible('pytorch', max_pin='x.x.x') }}
    - pytorch-gpu  # [cuda_compiler_version not in (undefined, 'None')]
    - pytorch-cpu  # [osx or cuda_compiler_version in (undefined, 'None')]
test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - benjaminrwilson
